[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_22']

[phases.build]
dependsOn = ['setup']
cmds = [
    'composer install --no-dev',
    'npm install --legacy-peer-deps',
    'npm run build',
    'mkdir -p database',
    'touch database/database.sqlite',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host 0.0.0.0 --port $PORT'